# Generated by Django 5.0.6 on 2024-06-10 18:00

import apps.halls.models
import core.utilities.models.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('scheme', models.ImageField(upload_to=apps.halls.models.get_hall_scheme_path)),
                ('upper_banner', models.ImageField(upload_to=apps.halls.models.get_hall_upper_banner_path)),
                ('capacity', models.SmallIntegerField(default=200)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinemas.cinema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall')),
            ],
        ),
    ]
