# Generated by Django 5.0.6 on 2024-06-11 20:45
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
