# Generated by Django 5.0.6 on 2024-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_remove_hall_capacity_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallimage',
            old_name='cinema',
            new_name='hall',
        ),
        migrations.AddField(
            model_name='seat',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
