# Generated by Django 5.0.6 on 2024-06-27 10:36

import core.utilities.models.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_page_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('can_be_deleted', models.BooleanField(default=True)),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
    ]
