# Generated by Django 5.0.6 on 2024-06-27 17:49

import core.utilities.models.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('address_uk', models.TextField()),
                ('address_en', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('logo', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.contacts')),
            ],
        ),
    ]
