services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kinocms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: config/celery/Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./media:/code/media
    env_file:
      - .env
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: config/web/Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./media:/code/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./media:/code/media
      - ./static:/code/static
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
