# Generated by Django 5.0.6 on 2024-07-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        ('halls', '0004_rename_cinema_hallimage_hall_seat_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.SmallIntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall')),
            ],
        ),
    ]
