# Generated by Django 5.0.6 on 2024-06-10 18:00

import apps.cinemas.models
import core.utilities.models.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('features_uk', models.TextField()),
                ('features_en', models.TextField()),
                ('logo', models.ImageField(upload_to=apps.cinemas.models.get_cinema_logo_path)),
                ('upper_banner', models.ImageField(upload_to=apps.cinemas.models.get_cinema_upper_banner_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
            ],
        ),
    ]
