# Generated by Django 5.0.6 on 2024-06-29 11:44

import core.utilities.models.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('file', models.FileField(upload_to=core.utilities.models.upload_path.get_upload_path)),
            ],
        ),
    ]
