# Generated by Django 5.0.6 on 2024-05-31 22:06

import apps.banners.models
import core.utilities.models.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_rotation', models.PositiveSmallIntegerField(default=5)),
                ('are_banners_active', models.BooleanField(default=True)),
                ('advertisement_rotation', models.PositiveSmallIntegerField(default=5)),
                ('are_advertisements_active', models.BooleanField(default=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=apps.banners.models.get_background_image_path)),
                ('is_background_image', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
