# Generated by Django 5.0.6 on 2024-06-07 11:39

import core.utilities.models.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('trailer_url', models.URLField()),
                ('is_3d', models.BooleanField(default=False)),
                ('is_2d', models.BooleanField(default=False)),
                ('is_imax', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utilities.models.upload_path.get_upload_path)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
